### PR TITLE
Add SweetXml.transform_by/2.

### PR DESCRIPTION
**Pull request by seantanly**
Pull request for issue https://github.com/awetzel/sweet_xml/issues/24, to support complex value transformation.

### CODE REVIEW

**Comment by awetzel** [comment]
Hello @seantanly ,
I love your idea, just one remark : 

I would think as a user better that in case of list, transform_fun would be applied to all elements instead of applying it to the list (since the "maps" keywords apply to every element on a list).
https://github.com/seantanly/sweet_xml/blob/transform_by/lib/sweet_xml.ex#L407-L411

Do you agree ?

**Comment by seantanly** [comment]
Good catch. For simple case, applying the transform_fun to every element on list is more convenient. 

However, it could be semantically inconsistent. Transform by is meant to transform whatever raw output that SweetXpath produces, be it a list, nodes, string, float, integer, etc. This gives the most flexibility and allows easy compatibility with existing code.

If we treat list as a special case, and apply the transform_fun to each element instead, we would lose the ability to process the list as a whole, e.g. reducing a set of nodes into a single set of statistics. Existing code that does this will not be able to make use of it then.

**Comment by seantanly** [comment]
@awetzel I have just rebased the pull request based on master, the merge conflicts should be gone and tests should all pass now.

**Comment by awetzel** [comment]
OK published to `0.6` , there is only a missing README

**Comment by seantanly** [comment]
Do you mean there is a missing section explaining how to use `transform_by/2`? 

I have already taken the liberty and add a **Transform by** section in the README.md. Feel free to make any amendment/improvements. :)

**Comment by awetzel** [comment]
Ah ok perfect then :) I missed it

**Pull request merged**
